export default{
    login:'/api/SystemSettingApi/Login',//登录
    GetMenuListById:'/api/SystemSettingApi/GetMenuListById',//获取动态路由   
    GetAdminList:'/api/SystemSettingApi/GetAdminList',//获取管理员列表
    GetRoleList:'/api/SystemSettingApi/GetRoleList',//获取角色列表
    AddAdmin:'/api/SystemSettingApi/AddAdmin',//添加管理员
    UpdateAdmin:'/api/SystemSettingApi/UpdateAdmin',//修改管理员信息
    DeleteAdminByIds:'/api/SystemSettingApi/DeleteAdminByIds',//根据id数组批量删除管理员信息
    AddRole:'/api/SystemSettingApi/AddRole',//添加角色信息
    UpdateRole:'/api/SystemSettingApi/UpdateRole',//修改角色信息
    DeleteRoleByIds:'/api/SystemSettingApi/DeleteRoleByIds',//根据id数组批量删除管理员信息
    GetMenuIdsByRoleId:'/api/SystemSettingApi/GetMenuIdsByRoleId',//根据角色id获取菜单id列表
    SetPower:'/api/SystemSettingApi/SetPower',//设置权限  
    GetGetlncmenu:'/api/TeamNoApi/Getlncmenu',//获取单位列表
    GetMonthofDay:'/api/PersonNoApi/GetMonthofDay',//获取个人体检号源
    GetMonthofDayT:'api/TeamNoApi/GetMonthofDayT',  
    SetPower:'/api/SystemSettingApi/SetPower',//设置权限    
    GetBooknosum:"/api/PersonNoApi/GetBooknosum",//设置预留个检号源
    GetTeamSumnosumm:"/api/TeamNoApi/GetTeamSumnosumm",//设置团体预留号源
    UpdateBooknoTotalTj:"/api/PersonNoApi/UpdateBooknoTotalTTj",//修改个检号源
    UpdateBooknoTotalTTj:"/api/TeamNoApi/UpdateBooknoTotalTj",
    AddLnc:'/api/BackProtectApi/AddLnc',//新增单位信息
    DeleteById:'/api/BackProtectApi/DeleteById',//删除单位信息
    UpdateLnc:'/api/BackProtectApi/UpdateLnc',//修改单位信息
    GetLncList:'/api/BackProtectApi/GetLncList',//获取所有单位  
    GetUserInfoList:'/api/BackProtectApi/GetAllUserInfo',//获取所有用户信息
    Timeslot:"/api/TeamNoApi/Timeslot",
    GetTable:'/api/BackProtectApi/GetTable',//导出表格数据
    GetPersonOrder:'/api/BackProtectApi/GetPersonOrder',//获取个检订单
    GetGroupOrder:'/api/BackProtectApi/GetGroupOrder',//获取团检订单    
    CancelPerOrder:'/api/BackProtectApi/CancelPersonalOrder',//撤销个检订单
    CancelGrpOrder:'/api/BackProtectApi/CancelGroupOrder',//撤销团检订单
    SyncLnc:'/api/BackProtectApi/SyncLnc',//同步单位
    pay:'/api/PayApi/Getpayy',//获取个检订单
}